const github = "https://github.com/alanthssss/sweetgold";
const milestones = [
  ["M4", "模仿学习 Imitation", "行为克隆 Behavior Cloning + DAgger"],
  ["M7", "去中心化 Decentralize", "局部行动者，全局评论家"],
  ["M10–12", "诚实失败 Fail honestly", "完整保留鲁棒性缺口"],
  ["M14", "通过门槛 Pass gates", "分层返航控制"],
  ["M15", "循证决策 Evidence", "可审计智能体工作流"],
];

export default function ChineseHome() {
  return <main>
    <nav className="nav shell" aria-label="主导航"><a className="brand" href="#top"><span className="brand-mark">SG</span><span>SweetGold</span></a><div className="nav-links"><a href="#start-here">从这里开始</a><a href="#impact">实际意义</a><a href="#evidence">实验依据</a><a href="#arena">策略竞技场</a><a href="#engineering">工程保障</a><a href="#start">快速开始</a><a className="language-switch" href="/" lang="en">English</a><a className="nav-cta" href={github}>GitHub ↗</a></div></nav>
    <section className="hero shell" id="top">
      <div className="hero-copy"><p className="eyebrow"><span /> 开源多智能体 AI 实验室 / OPEN-SOURCE MULTI-AGENT AI LAB</p><h1>训练一个蜂群，<br />让它在<em>未知环境</em>中生存。</h1><p className="lede">这是一个确定性蜂群模拟器：策略在完全相同的世界中竞争，学习策略必须通过预先声明的安全门槛，失败实验也会永久留在记录里。</p><div className="hero-actions"><a className="button primary" href="#start-here">先理解项目 <span>→</span></a><a className="button secondary" href={github}>查看源码 <span>↗</span></a></div><div className="proof-strip"><div><strong>53</strong><span>项测试通过 / tests</span></div><div><strong>6</strong><span>种审计场景 / scenarios</span></div><div><strong>Apache 2.0</strong><span>开源许可 / open source</span></div></div></div>
      <div className="colony-card" aria-label="蜂群模拟示意图"><div className="card-top"><span>蜂群 COLONY / 042</span><span className="live">● 运行中 LIVE</span></div><div className="sim-grid"><span className="hive">⬡</span><span className="flower f1">✦</span><span className="flower f2">✦</span><span className="flower f3">✦</span><span className="flower f4">✦</span><span className="bee b1">●</span><span className="bee b2">●</span><span className="bee b3">●</span><span className="bee b4">●</span><i className="trail t1" /><i className="trail t2" /><i className="trail t3" /></div><div className="sim-stats"><div><span>蜂蜜 HONEY</span><strong>223.68</strong><small>+52.6%</small></div><div><span>存活 SURVIVAL</span><strong>100%</strong><small>6 / 6</small></div><div><span>无效动作 INVALID</span><strong>0.00%</strong><small>安全 SAFE</small></div></div></div>
    </section>
    <section className="orientation shell" id="start-here"><div className="section-heading orientation-heading"><p className="eyebrow"><span /> 第一次来？先理解问题，再看术语</p><h2>一个蜜蜂小游戏，<br />一个严肃的协作问题。</h2></div><div className="plain-story"><article><b>01</b><h3>先建立世界</h3><p>蜂巢、花朵、能量、天气和几只虚拟蜜蜂。季节结束后，统计蜂蜜、存活和无效动作。</p></article><article><b>02</b><h3>尝试不同思维</h3><p>人工规则和学习策略解决同一个问题：各自行动，同时不浪费蜂群共享资源。</p></article><article><b>03</b><h3>参加同一场考试</h3><p>相同随机种子重建相同世界，策略不能仅仅因为拿到更简单的地图而获胜。</p></article><article><b>04</b><h3>带着证据发布</h3><p>预先声明的门槛、隔离的最终测试、模型哈希和失败记录，让晋级结果可追溯。</p></article></div><div className="reader-routes" aria-label="选择阅读路线"><div><span>我不熟悉 AI</span><strong>先理解游戏和问题</strong><a href={`${github}/blob/main/docs/getting-started.zh-CN.md`}>阅读零基础指南 →</a></div><div><span>我是 ML 从业者</span><strong>查看训练与证据</strong><a href={`${github}/blob/main/docs/models/README.zh-CN.md`}>打开模型目录 →</a></div><div><span>我是 DEVOPS / MLOPS 从业者</span><strong>追踪交付与控制</strong><a href={`${github}/blob/main/HANDOFF.zh-CN.md`}>阅读工程交接 →</a></div></div><p className="concept-line"><strong>完整路线：</strong>蜂群模拟器 → 规则基线 → 学习策略 → 公平考试 → 有证据的发布。</p></section>
    <section className="impact shell" id="impact"><div className="section-heading"><p className="eyebrow"><span /> 蜜蜂之外，为什么有意义</p><h2>用一个小世界，<br />训练高要求的工程习惯。</h2></div><p className="impact-lede">SweetGold 不是在销售蜜蜂策略。它用一个端到端系统，把协作、公平评测、模型晋级和审计证据变得可理解。工作流可能迁移，但每个行业声明仍需领域验证。</p><div className="impact-grid"><article><span>今天的实际价值</span><h3>看懂完整 AI 生命周期</h3><p>从模拟器和基线，到学习策略、隔离最终测试、经验证模型和可审计决策。</p></article><article><span>潜在迁移场景</span><h3>共享资源下的协作</h3><p>仓储与机器人集群、无人机巡检、交通研究、游戏、AI 评测和技术教育。</p></article><article><span>客户假设</span><h3>教授、测试或治理 AI 的团队</h3><p>大学、企业学院、ML 平台、治理团队、仿真研发团队和技术咨询机构。</p></article></div><div className="truth-grid"><div><span>优势</span><strong>证据本身就是产品</strong><p>确定性比较、预先声明门槛、失败保留、模型完整性和双语解释形成一套连贯工作流。</p></div><div><span>限制</span><strong>当前领域仍是代理场景</strong><p>尚无客户调研、付费试点、真实车队集成、多用户加固或经过衡量的业务结果。</p></div></div><div className="commercial-path"><div><span>01</span><strong>访谈</strong><p>验证一个反复出现且紧迫的买方问题。</p></div><div><span>02</span><strong>迁移</strong><p>接入一个外部或客户仿真器。</p></div><div><span>03</span><strong>试点</strong><p>衡量时间、缺陷或审计成本下降。</p></div><div><span>04</span><strong>产品化</strong><p>只标准化反复出现的核心。</p></div></div><p className="impact-boundary">最可信的第一条路径是教育与能力建设，其次是适配器式评测和晋级工具包。在出现领域证据前，直接工业控制仍然只是一个假设。</p><a className="impact-link" href={`${github}/blob/main/docs/impact-and-roadmap.zh-CN.md`}>阅读完整客户、优劣势、商业化与路线分析 →</a></section>
    <section className="strategy-summary shell" aria-label="竞争与开源策略"><div className="strategy-band"><div><span>竞争方式</span><strong>占据评测与晋级层</strong><p>集成 PettingZoo、RLlib、Isaac Lab 和模型注册表，不竞争环境数量、算法广度、GPU 规模或通用跟踪。</p></div><div><span>开源现实</span><strong>代码可以被复制</strong><p>Apache-2.0 允许合规使用、修改、再分发和商业复用。防御来自可信上游、品牌、适配器、证据、社区和客户上下文。</p></div><div><span>下一项特性</span><strong>先证明可迁移</strong><p>客户访谈后，接入一个 PettingZoo 环境并发布稳定证据格式，再考虑更多算法或 SaaS 仪表盘。</p></div></div></section>
    <section className="current-outcome shell" id="evidence"><div className="section-heading"><p className="eyebrow"><span /> 产品工作流 · M15</p><h2>输入实验依据，<br />输出可审计决策。</h2></div><div className="outcome-grid"><article><span>决策目标 OBJECTIVES</span><strong>3</strong><p>平衡 · 产量 · 安全</p></article><article><span>安全约束 CONSTRAINTS</span><strong>2</strong><p>存活率 · 无效动作率</p></article><article><span>证据格式 EVIDENCE</span><strong>2</strong><p>JSON · Markdown</p></article><article><span>决策方式 DECISION</span><strong>确定性</strong><p>明确推荐或明确拒绝</p></article></div><p className="method-note">M15 从已有策略中做选择，不训练新策略；M16 是最新工程里程碑。</p></section>
    <section className="evidence shell"><div className="section-heading"><p className="eyebrow"><span /> 最新晋级策略 · M14</p><h2>最新策略的<br />正式性能结果。</h2></div><div className="scorecard"><div className="score-main"><strong>148.47%</strong><span>蜂蜜中位数 / Assignment 基线</span></div><div className="score"><strong>101.16%</strong><span>最差场景产量</span><small>花蜜稀缺 scarce nectar</small></div><div className="score"><strong>100%</strong><span>最低存活率</span><small>所有场景</small></div><div className="score"><strong>0%</strong><span>无效动作率</span><small>所有场景</small></div></div><p className="method-note">M14 · 每个场景 50 个从未使用的最终种子 · 只用相互隔离的验证种子选型 · M15 不改变这些结果</p></section>
    <section className="arena shell" id="arena"><div className="arena-panel"><div className="arena-copy"><p className="eyebrow"><span /> 策略竞技场 / STRATEGY ARENA</p><h2>同一个世界，<br />不同的思维。</h2><p>让两个策略从同一随机种子出发，实时比较蜂蜜、存活率、效率和无效动作，并回放每一帧。</p><ul><li><b>01</b> 配对种子锦标赛 Matched-seed tournament</li><li><b>02</b> 已验证模型注册表 Verified registry</li><li><b>03</b> 可审计智能体建议 Auditable recommendation</li></ul></div><div className="matchup"><div className="match-head"><span>比赛 MATCH 04 / SEED 202607</span><span>季节 SEASON 86%</span></div><div className="lane"><div><span>A</span><b>分层 CTDE</b></div><strong>218</strong></div><div className="bar"><i style={{width:"88%"}} /></div><div className="lane"><div><span>B</span><b>任务分配 Assignment</b></div><strong>146</strong></div><div className="bar muted"><i style={{width:"59%"}} /></div><div className="match-result"><span>蜂蜜差 Δ HONEY</span><strong>+72</strong><span>所有蜜蜂存活</span></div></div></div></section>
    <section className="engineering shell" id="engineering"><div className="section-heading"><p className="eyebrow"><span /> 工程保障 / ENGINEERING GUARANTEES</p><h2>把研究严谨性，<br />构建进系统。</h2></div><div className="engineering-grid"><article><b>01</b><h3>确定性执行</h3><p>种子化环境和配对回合让每次策略比较都能重复。</p></article><article><b>02</b><h3>评测数据隔离</h3><p>预检阻止训练、验证、选型和最终测试之间发生泄漏。</p></article><article><b>03</b><h3>策略即代码的门槛</h3><p>置信度、产量和安全阈值保存在有版本的实验配置中。</p></article><article><b>04</b><h3>经验证的模型供应链</h3><p>不可变发布、精确大小、SHA-256、许可证和原子安装保护检查点。</p></article><article><b>05</b><h3>可追溯产物</h3><p>JSON 运行包保存提交、环境、种子清单、指标和决策链接。</p></article><article><b>06</b><h3>自动化回归防线</h3><p>核心测试和端到端 ML 冒烟流水线进入 CI，失败审计保持可见。</p></article></div><p className="engineering-boundary">采用企业级工程实践，同时明确边界：内置服务器是本地实验接口，不是经过加固的多用户生产服务。</p><div className="hardware-note"><span>最新工程里程碑 · M16</span><strong>CPU、Apple MPS 和 NVIDIA CUDA 都是显式执行目标。</strong><p>在实测的小型行为克隆任务中，M1 Pro CPU 约比 MPS 快 6.4 倍，因为加速器开销超过了有效并行计算。决策依据是硬件证据，而不是“GPU 永远更快”。</p><a href={`${github}/blob/main/docs/hardware-benchmark.zh-CN.md`}>阅读硬件基准 →</a></div></section>
    <section className="journey shell"><div className="section-heading compact"><p className="eyebrow"><span /> 15 个里程碑，一条完整审计轨迹</p><h2>失败实验造就了最终策略。</h2></div><div className="milestones">{milestones.map(([id,title,text]) => <article key={id}><span>{id}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="failure-note">M10–M12 没有通过预先声明的门槛；SweetGold 记录原因，没有事后降低标准。</p><p className="failure-note"><strong>M14</strong> 是最新晋级策略；<strong>M15</strong> 是最新完成的工作流，把 Arena 证据转化为受约束、可审计的策略建议。</p></section>
    <section className="start shell" id="start"><div><p className="eyebrow"><span /> 零依赖启动 / ZERO-DEPENDENCY START</p><h2>三条命令，<br />从源码进入蜂群。</h2></div><div className="terminal"><div className="terminal-top"><i /><i /><i /><span>sweetgold — zsh</span></div><pre><code><b>$</b> git clone https://github.com/alanthssss/sweetgold.git{`\n`}<b>$</b> cd sweetgold{`\n`}<b>$</b> python3 main.py play --port 8080{`\n\n`}<span>✓ 策略竞技场已就绪：http://127.0.0.1:8080</span></code></pre></div></section>
    <footer className="shell"><div className="footer-brand"><span className="brand-mark">SG</span><div><strong>SweetGold</strong><p>让每个策略用证据赢得晋级。</p></div></div><div className="footer-links"><a href={github}>GitHub</a><a href={`${github}/releases`}>版本发布</a><a href={`${github}/blob/main/docs/models/hierarchical-return-ctde.zh-CN.md`}>模型卡</a></div><p className="copyright">Apache-2.0 · 全程公开构建</p></footer>
  </main>;
}
