const github = "https://github.com/alanthssss/sweetgold";
const milestones = [
  ["M4", "模仿学习 Imitation", "行为克隆 Behavior Cloning + DAgger"],
  ["M7", "去中心化 Decentralize", "局部行动者，全局评论家"],
  ["M10–12", "诚实失败 Fail honestly", "完整保留鲁棒性缺口"],
  ["M14", "通过门槛 Pass gates", "分层返航控制"],
  ["M15", "循证决策 Evidence", "可审计智能体工作流"],
];

export default function ChineseHome() {
  return <main>
    <nav className="nav shell" aria-label="主导航"><a className="brand" href="#top"><span className="brand-mark">SG</span><span>SweetGold</span></a><div className="nav-links"><a href="#evidence">实验依据</a><a href="#arena">策略竞技场</a><a href="#start">快速开始</a><a className="language-switch" href="/" lang="en">English</a><a className="nav-cta" href={github}>GitHub ↗</a></div></nav>
    <section className="hero shell" id="top">
      <div className="hero-copy"><p className="eyebrow"><span /> 开源多智能体 AI 实验室 / OPEN-SOURCE MULTI-AGENT AI LAB</p><h1>训练一个蜂群，<br />让它在<em>未知环境</em>中生存。</h1><p className="lede">这是一个确定性蜂群模拟器：策略在完全相同的世界中竞争，学习策略必须通过预先声明的安全门槛，失败实验也会永久留在记录里。</p><div className="hero-actions"><a className="button primary" href={github}>运行竞技场 <span>→</span></a><a className="button secondary" href={github}>查看源码 <span>↗</span></a></div><div className="proof-strip"><div><strong>45</strong><span>项测试通过 / tests</span></div><div><strong>6</strong><span>种审计场景 / scenarios</span></div><div><strong>Apache 2.0</strong><span>开源许可 / open source</span></div></div></div>
      <div className="colony-card" aria-label="蜂群模拟示意图"><div className="card-top"><span>蜂群 COLONY / 042</span><span className="live">● 运行中 LIVE</span></div><div className="sim-grid"><span className="hive">⬡</span><span className="flower f1">✦</span><span className="flower f2">✦</span><span className="flower f3">✦</span><span className="flower f4">✦</span><span className="bee b1">●</span><span className="bee b2">●</span><span className="bee b3">●</span><span className="bee b4">●</span><i className="trail t1" /><i className="trail t2" /><i className="trail t3" /></div><div className="sim-stats"><div><span>蜂蜜 HONEY</span><strong>223.68</strong><small>+52.6%</small></div><div><span>存活 SURVIVAL</span><strong>100%</strong><small>6 / 6</small></div><div><span>无效动作 INVALID</span><strong>0.00%</strong><small>安全 SAFE</small></div></div></div>
    </section>
    <section className="current-outcome shell" id="evidence"><div className="section-heading"><p className="eyebrow"><span /> 最新完成成果 · M15</p><h2>输入实验依据，<br />输出可审计决策。</h2></div><div className="outcome-grid"><article><span>决策目标 OBJECTIVES</span><strong>3</strong><p>平衡 · 产量 · 安全</p></article><article><span>安全约束 CONSTRAINTS</span><strong>2</strong><p>存活率 · 无效动作率</p></article><article><span>证据格式 EVIDENCE</span><strong>2</strong><p>JSON · Markdown</p></article><article><span>决策方式 DECISION</span><strong>确定性</strong><p>明确推荐或明确拒绝</p></article></div><p className="method-note">M15 是当前项目阶段：它从已有策略中做选择，不训练新策略。</p></section>
    <section className="evidence shell"><div className="section-heading"><p className="eyebrow"><span /> 最新晋级策略 · M14</p><h2>最新策略的<br />正式性能结果。</h2></div><div className="scorecard"><div className="score-main"><strong>148.47%</strong><span>蜂蜜中位数 / Assignment 基线</span></div><div className="score"><strong>101.16%</strong><span>最差场景产量</span><small>花蜜稀缺 scarce nectar</small></div><div className="score"><strong>100%</strong><span>最低存活率</span><small>所有场景</small></div><div className="score"><strong>0%</strong><span>无效动作率</span><small>所有场景</small></div></div><p className="method-note">M14 · 每个场景 50 个从未使用的最终种子 · 只用相互隔离的验证种子选型 · M15 不改变这些结果</p></section>
    <section className="arena shell" id="arena"><div className="arena-panel"><div className="arena-copy"><p className="eyebrow"><span /> 策略竞技场 / STRATEGY ARENA</p><h2>同一个世界，<br />不同的思维。</h2><p>让两个策略从同一随机种子出发，实时比较蜂蜜、存活率、效率和无效动作，并回放每一帧。</p><ul><li><b>01</b> 配对种子锦标赛 Matched-seed tournament</li><li><b>02</b> 已验证模型注册表 Verified registry</li><li><b>03</b> 可审计智能体建议 Auditable recommendation</li></ul></div><div className="matchup"><div className="match-head"><span>比赛 MATCH 04 / SEED 202607</span><span>季节 SEASON 86%</span></div><div className="lane"><div><span>A</span><b>分层 CTDE</b></div><strong>218</strong></div><div className="bar"><i style={{width:"88%"}} /></div><div className="lane"><div><span>B</span><b>任务分配 Assignment</b></div><strong>146</strong></div><div className="bar muted"><i style={{width:"59%"}} /></div><div className="match-result"><span>蜂蜜差 Δ HONEY</span><strong>+72</strong><span>所有蜜蜂存活</span></div></div></div></section>
    <section className="journey shell"><div className="section-heading compact"><p className="eyebrow"><span /> 15 个里程碑，一条完整审计轨迹</p><h2>失败实验造就了最终策略。</h2></div><div className="milestones">{milestones.map(([id,title,text]) => <article key={id}><span>{id}</span><h3>{title}</h3><p>{text}</p></article>)}</div><p className="failure-note">M10–M12 没有通过预先声明的门槛；SweetGold 记录原因，没有事后降低标准。</p><p className="failure-note"><strong>M14</strong> 是最新晋级策略；<strong>M15</strong> 是最新完成的工作流，把 Arena 证据转化为受约束、可审计的策略建议。</p></section>
    <section className="start shell" id="start"><div><p className="eyebrow"><span /> 零依赖启动 / ZERO-DEPENDENCY START</p><h2>三条命令，<br />从源码进入蜂群。</h2></div><div className="terminal"><div className="terminal-top"><i /><i /><i /><span>sweetgold — zsh</span></div><pre><code><b>$</b> git clone https://github.com/alanthssss/sweetgold.git{`\n`}<b>$</b> cd sweetgold{`\n`}<b>$</b> python3 main.py play --port 8080{`\n\n`}<span>✓ 策略竞技场已就绪：http://127.0.0.1:8080</span></code></pre></div></section>
    <footer className="shell"><div className="footer-brand"><span className="brand-mark">SG</span><div><strong>SweetGold</strong><p>让每个策略用证据赢得晋级。</p></div></div><div className="footer-links"><a href={github}>GitHub</a><a href={`${github}/releases`}>版本发布</a><a href={`${github}/blob/main/docs/models/hierarchical-return-ctde.zh-CN.md`}>模型卡</a></div><p className="copyright">Apache-2.0 · 全程公开构建</p></footer>
  </main>;
}
